
name: 'oncology_dbt'
version: '1.0.0'


profile: 'oncology_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  oncology_dbt:
    +materialized: view

vars:
  oncology_access_start_date: '2019-01-01'
  oncology_access_provider_name_regex: '\\[(.*?)\\]'
